import { defineConfig } from "@umijs/max";

const backendPort = process.env.BACKEND_PORT ?? "8080";

/**
 * Ant Design Pro v6 runtime configuration.
 *
 * The ERP keeps its existing React Router route tree in `src/App.tsx` while
 * Umi Max owns application bootstrapping, development proxying, and builds.
 * This lets us adopt the Pro v6 toolchain without disrupting ERP URLs.
 */
export default defineConfig({
  title: "AIERP",
  routes: [
    // Public entry points are now owned by Umi's route manifest. The legacy
    // App route remains as a compatibility fallback while feature modules
    // move to the same manifest in batches.
    { path: "/login", component: "@/pages/auth/Login" },
    { path: "/inquiry", component: "@/pages/public/InquiryPortal" },
    {
      path: "/",
      component: "@/layouts/ErpRouteLayout",
      routes: [
        { path: "", component: "@/pages/dashboard/index" },
        { path: "sales", redirect: "/sales/dashboard" },
        { path: "customers/stats", component: "@/pages/customers/CustomerDashboard" },
        { path: "customers", component: "@/pages/customers/CustomerListPage" },
        { path: "customers/new", component: "@/pages/customers/CustomerNew" },
        { path: "customers/:id", component: "@/pages/customers/CustomerDetail" },
        { path: "customers/intelligence", component: "@/pages/customers/CustomerIntelligenceDashboard" },
        { path: "customers/workbench", component: "@/pages/customers/CustomerAIWorkbench" },
        { path: "customers/segments", component: "@/pages/customers/CustomerSegments" },
        { path: "customers/follow-ups", component: "@/pages/customers/CustomerFollowUpsPage" },
        { path: "customers/:customerId/follow-ups", component: "@/pages/customers/FollowUpList" },
        { path: "customers/:customerId/follow-ups/new", component: "@/pages/customers/FollowUpForm" },
        { path: "customers/:customerId/follow-ups/:followupId/edit", component: "@/pages/customers/FollowUpForm" },
        { path: "customers/assignment-rules", component: "@/pages/customers/AssignmentRulesPage" },
        { path: "customers/release-rules", component: "@/pages/customers/ReleaseRulesPage" },
        { path: "customers/transfer-requests", component: "@/pages/customers/OwnerTransferRequestsPage" },
        { path: "sales/dashboard", component: "@/pages/sales/SalesDashboard" },
        { path: "sales/opportunities", component: "@/pages/sales/OpportunityList" },
        { path: "sales/opportunities/new", component: "@/pages/sales/OpportunityForm" },
        { path: "sales/opportunities/:id", component: "@/pages/sales/OpportunityDetail" },
        { path: "sales/opportunities/:id/edit", component: "@/pages/sales/OpportunityForm" },
        { path: "sales/quotations", component: "@/pages/sales/QuotationList" },
        { path: "sales/quotations/new", component: "@/pages/sales/QuotationForm" },
        { path: "sales/quotations/:id", component: "@/pages/sales/QuotationDetail" },
        { path: "sales/quotations/:id/edit", component: "@/pages/sales/QuotationForm" },
        { path: "sales/orders", component: "@/pages/sales/SalesOrderList" },
        { path: "sales/orders/new", component: "@/pages/sales/SalesOrderForm" },
        { path: "sales/orders/:id", component: "@/pages/sales/SalesOrderDetail" },
        { path: "sales/orders/:id/edit", component: "@/pages/sales/SalesOrderForm" },
        { path: "sales/delivery-notes", component: "@/pages/sales/DeliveryNoteList" },
        { path: "sales/delivery-notes/new", component: "@/pages/sales/DeliveryNoteForm" },
        { path: "sales/delivery-notes/:id", component: "@/pages/sales/DeliveryNoteDetail" },
        { path: "sales/delivery-notes/:id/edit", component: "@/pages/sales/DeliveryNoteForm" },
        { path: "sales/invoices", component: "@/pages/sales/InvoiceList" },
        { path: "sales/invoices/new", component: "@/pages/sales/InvoiceForm" },
        { path: "sales/invoices/:id", component: "@/pages/sales/InvoiceDetail" },
        { path: "sales/invoices/:id/edit", component: "@/pages/sales/InvoiceForm" },
        { path: "sales/payments", component: "@/pages/sales/PaymentList" },
        { path: "sales/payments/new", component: "@/pages/sales/PaymentForm" },
        { path: "sales/payments/:id/edit", component: "@/pages/sales/PaymentForm" },
        { path: "sales/purchase-orders", component: "@/pages/sales/PurchaseOrderList" },
        { path: "sales/purchase-orders/new", component: "@/pages/sales/PurchaseOrderForm" },
        { path: "sales/purchase-orders/:id", component: "@/pages/sales/PurchaseOrderDetail" },
        { path: "sales/purchase-orders/:id/edit", component: "@/pages/sales/PurchaseOrderForm" },
        { path: "sales/contracts", component: "@/pages/sales/ContractList" },
        { path: "sales/contracts/new", component: "@/pages/sales/ContractForm" },
        { path: "sales/contracts/:id", component: "@/pages/sales/ContractDetail" },
        { path: "sales/contracts/:id/edit", component: "@/pages/sales/ContractForm" },
        { path: "sales/targets", component: "@/pages/sales/TargetList" },
        { path: "sales/targets/new", component: "@/pages/sales/TargetForm" },
        { path: "sales/targets/:id/edit", component: "@/pages/sales/TargetForm" },
        { path: "sales/inquiry", component: "@/pages/sales/InquiryAutoReply" },
        { path: "products", component: "@/pages/products/index" },
        { path: "products/price-import", component: "@/pages/products/PriceImport" },
        { path: "products/inventory", component: "@/pages/products/InventoryManage" },
        { path: "products/:id", component: "@/pages/products/ProductDetail" },
        { path: "products/:id/edit", component: "@/pages/products/ProductEdit" },
        { path: "products/:id/360", component: "@/pages/products/Product360" },
        { path: "suppliers", component: "@/pages/suppliers/index" },
        { path: "suppliers/stats", component: "@/pages/suppliers/SupplierDashboard" },
        { path: "suppliers/compare", component: "@/pages/suppliers/SupplierCompare" },
        { path: "suppliers/:id", component: "@/pages/suppliers/SupplierDetail" },
        { path: "suppliers/:id/360", component: "@/pages/suppliers/Supplier360" },
        { path: "brands", component: "@/pages/brands/index" },
        { path: "brands/stats", component: "@/pages/brands/BrandDashboard" },
        { path: "brands/:id", component: "@/pages/brands/BrandDetail" },
        { path: "brands/:id/edit", component: "@/pages/brands/BrandEdit" },
        { path: "inventory", component: "@/pages/inventory/index" },
        { path: "inventory/expiring", component: "@/pages/inventory/BatchExpiring" },
        { path: "inventory/batches/:id/recall", component: "@/pages/inventory/BatchRecall" },
        { path: "warehouse", component: "@/pages/warehouse/index" },
        { path: "warehouse/warehouses", component: "@/pages/warehouse/WarehouseList" },
        { path: "warehouse/inventory-ledger", component: "@/pages/warehouse/InventoryLedger" },
        { path: "warehouse/inventory-batches", component: "@/pages/warehouse/InventoryBatches" },
        { path: "inventory/batches/:id/traceability", component: "@/pages/warehouse/BatchTraceability" },
        { path: "dashboard/watchtower", component: "@/pages/dashboard/WatchtowerDashboard" },
        { path: "dashboard/global360", component: "@/pages/dashboard/Global360" },
        { path: "settings", component: "@/pages/settings/index" },
        { path: "system/users", component: "@/pages/system/users/UserList" },
        { path: "system/roles", component: "@/pages/system/Roles" },
        { path: "system/approvals", component: "@/pages/system/ApprovalList" },
        { path: "system/approval-rules", component: "@/pages/system/ApprovalRules" },
        { path: "system/audit-logs", component: "@/pages/system/AuditLogList" },
        { path: "system/audit", component: "@/pages/system/AuditLogViewer" },
        { path: "system/uoms", component: "@/pages/system/UomsList" },
        { path: "procurement/dashboard", component: "@/pages/procurement/ProcurementDashboard" },
        { path: "reports/sales", component: "@/pages/reports/ReportSales" },
        { path: "reports/ar", component: "@/pages/reports/ReportAR" },
        { path: "reports/inventory", component: "@/pages/reports/ReportInventory" },
        { path: "reports/procurement", component: "@/pages/reports/ReportProcurement" },
        { path: "reports/ap", component: "@/pages/reports/ReportAP" },
        { path: "data/import-export", component: "@/pages/import-export/index" },
        { path: "finance/accounts", component: "@/pages/finance/AccountList" },
        { path: "finance/journal-entries", component: "@/pages/finance/JournalEntryList" },
        { path: "finance/journal-entries/new", component: "@/pages/finance/JournalEntryForm" },
        { path: "finance/journal-entries/:id", component: "@/pages/finance/JournalEntryForm" },
        { path: "finance/pnl", component: "@/pages/finance/ProfitLoss" },
        { path: "finance/commissions", component: "@/pages/finance/CommissionList" },
        { path: "finance/commission-schemes", component: "@/pages/finance/CommissionSchemeList" },
        { path: "ai/chat", component: "@/pages/ai/Chat" },
        { path: "notifications", component: "@/pages/notifications/index" },
        { path: "tickets", component: "@/pages/tickets/TicketList" },
        { path: "tickets/new", component: "@/pages/tickets/TicketForm" },
        { path: "tickets/:id", component: "@/pages/tickets/TicketDetail" },
        { path: "tickets/:id/edit", component: "@/pages/tickets/TicketForm" },
      ],
    },
    { path: "/*", component: "@/App" },
  ],
  fastRefresh: true,
  // Umi's esbuild helper checker requires IIFE minification when the app
  // contains many lazy-loaded chunks; without it production builds fail
  // after webpack compilation with duplicate helper names.
  esbuildMinifyIIFE: true,
  reactQuery: {},
  antd: {
    configProvider: {
      theme: { cssVar: true },
    },
  },
  proxy: {
    "/api": {
      target: `http://localhost:${backendPort}`,
      changeOrigin: true,
    },
  },
});
