-- Brand Hub: P0+P1 fields upgrade
ALTER TABLE brands ADD COLUMN IF NOT EXISTS code VARCHAR(50);
ALTER TABLE brands ADD COLUMN IF NOT EXISTS short_name VARCHAR(100);
ALTER TABLE brands ADD COLUMN IF NOT EXISTS logo VARCHAR(500);
ALTER TABLE brands ADD COLUMN IF NOT EXISTS brand_type VARCHAR(50);
ALTER TABLE brands ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'active';
ALTER TABLE brands ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE brands ADD COLUMN IF NOT EXISTS level VARCHAR(10);
ALTER TABLE brands ADD COLUMN IF NOT EXISTS positioning VARCHAR(50);
ALTER TABLE brands ADD COLUMN IF NOT EXISTS owner VARCHAR(100);
ALTER TABLE brands ADD COLUMN IF NOT EXISTS product_lines TEXT;
ALTER TABLE brands ADD COLUMN IF NOT EXISTS target_markets TEXT;
ALTER TABLE brands ADD COLUMN IF NOT EXISTS supplier_id INTEGER REFERENCES suppliers(id);
ALTER TABLE brands ADD COLUMN IF NOT EXISTS manufacturer_name VARCHAR(255);
ALTER TABLE brands ADD COLUMN IF NOT EXISTS authorization_status VARCHAR(50);
ALTER TABLE brands ADD COLUMN IF NOT EXISTS lifecycle_stage VARCHAR(50);
ALTER TABLE brands ADD COLUMN IF NOT EXISTS is_automotive BOOLEAN DEFAULT FALSE;
ALTER TABLE brands ADD COLUMN IF NOT EXISTS moq INTEGER;
ALTER TABLE brands ADD COLUMN IF NOT EXISTS lead_time_days INTEGER;
ALTER TABLE brands ADD COLUMN IF NOT EXISTS risk_level VARCHAR(50);
ALTER TABLE brands ADD COLUMN IF NOT EXISTS rohs_status VARCHAR(50);
ALTER TABLE brands ADD COLUMN IF NOT EXISTS ai_keywords TEXT;
ALTER TABLE brands ADD COLUMN IF NOT EXISTS risk_score DOUBLE PRECISION;
ALTER TABLE brands ADD COLUMN IF NOT EXISTS alternative_brands TEXT;
ALTER TABLE brands ADD COLUMN IF NOT EXISTS embedding vector(1024);

CREATE UNIQUE INDEX IF NOT EXISTS ix_brands_code ON brands(code) WHERE code IS NOT NULL;
