"""Back-compat shim — re-exports the public surface of ``app.services.pdf``.

The PDF service was split from a 1289-line monolith into a
``pdf/`` subpackage. This shim keeps the legacy import path
``from app.services.pdf_service import X`` working so existing
callers don't need to change.

New code should import directly from ``app.services.pdf``.
"""
from __future__ import annotations

from app.services.pdf import (  # noqa: F401  (re-export back-compat)
    REPORTLAB_AVAILABLE,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
    colors,
    A4,
    ParagraphStyle,
    getSampleStyleSheet,
    mm,
    Paragraph,
    CHINESE_FONT_KEYWORDS,
    CHINESE_FONT_PATHS,
    FALLBACK_FONT,
    PARTIAL_FONT_KEYWORDS,
    _as_decimal,
    _date_text,
    _days_until,
    _default_terms,
    _get_chinese_font,
    get_chinese_font,
    _item_total,
    _line_hint,
    _margin_rate,
    _money,
    _money_upper_cn,
    _money_text,
    _money_upper_cn_text,
    _order_risk_text,
    _order_summary_lines,
    _pdf_escape,
    _pdf_options,
    _pdf_text,
    _percent,
    _quote_risk_text,
    _smart_summary_lines,
    _status_label,
    as_decimal,
    date_text,
    days_until,
    default_terms,
    generate_basic_order_pdf,
    generate_basic_pdf,
    generate_quotation_pdf,
    generate_sales_order_pdf,
    item_total,
    line_hint,
    margin_rate,
    money,
    money_text,
    money_upper_cn,
    order_risk_text,
    order_summary_lines,
    pdf_escape,
    pdf_options,
    pdf_text,
    percent,
    quote_risk_text,
    smart_summary_lines,
    status_label,
)


__all__ = [
    "REPORTLAB_AVAILABLE",
    "generate_quotation_pdf",
    "generate_sales_order_pdf",
    "generate_basic_pdf",
    "generate_basic_order_pdf",
    "money",
    "money_upper_cn",
    "money_text",
    "as_decimal",
    "date_text",
    "days_until",
    "status_label",
    "quote_risk_text",
    "order_risk_text",
    "line_hint",
    "item_total",
    "margin_rate",
    "percent",
    "smart_summary_lines",
    "order_summary_lines",
    "pdf_text",
    "pdf_escape",
    "pdf_options",
    "default_terms",
    "_money",
    "_money_upper_cn",
    "_money_text",
    "_money_upper_cn_text",
    "_as_decimal",
    "_date_text",
    "_days_until",
    "_status_label",
    "_quote_risk_text",
    "_order_risk_text",
    "_line_hint",
    "_item_total",
    "_margin_rate",
    "_percent",
    "_smart_summary_lines",
    "_order_summary_lines",
    "_pdf_text",
    "_pdf_escape",
    "_pdf_options",
    "_default_terms",
    "_get_chinese_font",
    "get_chinese_font",
    "SimpleDocTemplate",
    "Spacer",
    "Table",
    "TableStyle",
    "colors",
    "A4",
    "ParagraphStyle",
    "getSampleStyleSheet",
    "mm",
    "Paragraph",
    "CHINESE_FONT_PATHS",
    "CHINESE_FONT_KEYWORDS",
    "PARTIAL_FONT_KEYWORDS",
    "FALLBACK_FONT",
]
